# Generated by Django 3.2.19 on 2023-07-01 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='url',
            field=models.URLField(default='www.x.com', verbose_name='URL'),
            preserve_default=False,
        ),
    ]
