# Generated by Django 3.2.19 on 2023-07-01 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0002_cv_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='url',
        ),
    ]
