# Generated by Django 3.2.19 on 2023-07-02 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cvs', '0003_remove_cv_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('type', models.IntegerField(choices=[(1, 'Fullname'), (2, 'Email'), (3, 'Phone'), (5, 'Linkedin'), (6, 'Date of birth'), (7, 'Age'), (8, 'Website')], default=1, verbose_name='Type')),
                ('content', models.CharField(blank=True, max_length=255, verbose_name='Content')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bio_cv', to='cvs.cv', verbose_name='Bio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Bio model',
                'verbose_name_plural': 'Bios',
            },
        ),
    ]
