# Generated by Django 3.2.19 on 2023-07-02 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0004_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bio_cv', to='cvs.cv', verbose_name='CV'),
        ),
        migrations.AlterField(
            model_name='bio',
            name='type',
            field=models.IntegerField(choices=[(1, 'Fullname'), (2, 'Email'), (3, 'Phone'), (4, 'Date of birth'), (5, 'Age'), (6, 'Website')], default=1, verbose_name='Type'),
        ),
    ]
