# Generated by Django 3.2.19 on 2023-07-02 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cvs', '0006_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=50, verbose_name='Content')),
                ('position', models.IntegerField(choices=[(1, 'Software Engineer'), (2, 'Data Scientist'), (3, 'Product Manager'), (4, 'UX/UI Designer'), (5, 'DevOps Engineer'), (6, 'Quality Assurance Engineer'), (7, 'Systems Administrator'), (8, 'Data Engineer'), (9, 'Security Analyst'), (10, 'Technical Support Specialist'), (11, 'Project Manager'), (12, 'Sales Engineer')], default=1, verbose_name='Proficiency')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_working_on_current_company', models.BooleanField(default=False)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_cv', to='cvs.cv', verbose_name='CV')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Experience model',
                'verbose_name_plural': 'Experiences',
            },
        ),
    ]
