# Generated by Django 3.2.19 on 2023-07-02 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0007_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bio',
            name='user',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='user',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='user',
        ),
    ]
