# Generated by Django 3.2.19 on 2023-07-02 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0010_auto_20230702_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='issuer_year',
        ),
        migrations.AddField(
            model_name='certificate',
            name='issuer_data',
            field=models.DateField(blank=True, null=True, verbose_name='Issuer Date'),
        ),
    ]
