# Generated by Django 3.2.19 on 2023-07-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0012_rename_issuer_data_certificate_issuer_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='graduated_year',
        ),
        migrations.AddField(
            model_name='education',
            name='graduated_date',
            field=models.DateField(blank=True, null=True, verbose_name='Graduated date'),
        ),
    ]
