# Generated by Django 3.2.19 on 2023-07-02 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0013_auto_20230702_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.IntegerField(choices=[(1, 'Associate'), (2, 'Certificate'), (3, 'Diploma'), (4, 'Bachelor'), (5, 'Master'), (6, 'Doctorate'), (7, 'Other')], default=4, verbose_name='Degree'),
        ),
    ]
