# Generated by Django 3.2.19 on 2023-07-03 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
