# Generated by Django 3.2.19 on 2023-07-03 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('links', '0002_alter_link_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='contenttypes.contenttype', verbose_name='Content Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='object_id',
            field=models.CharField(db_index=True, default=1, max_length=100, verbose_name='Object ID'),
            preserve_default=False,
        ),
    ]
